name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]

    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=blob --shard=${{ matrix.shard }}/3
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Upload blob report
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shard }}
          path: blob-report
          retention-days: 1

  merge-reports:
    needs: playwright-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - run: npm ci

      - name: Download blob reports
        uses: actions/download-artifact@v4
        with:
          path: blob-report
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge reports
        run: npx playwright merge-reports --reporter=html ./blob-report

      - name: Upload Final HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-merged-html-report
          path: playwright-report/
          retention-days: 30